# Generated by Django 4.2 on 2024-02-05 12:28

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('answer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_type', models.CharField(blank=True, choices=[('Reading', 'Reading'), ('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Writing', 'Writing')], default='Reading', help_text='(Reading, Listening, Speaking, Writing)', max_length=200, null=True)),
                ('passage', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contents')),
                ('no_of_questions', models.IntegerField(blank=True, default=4, null=True)),
                ('question', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('block_type', models.CharField(blank=True, choices=[('Practice', 'Practice'), ('Full Length', 'Full Length'), ('Assignments', 'Assignments')], max_length=200, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=200, null=True)),
                ('block_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='examblockaudio/')),
            ],
            options={
                'verbose_name': 'Exam_Block',
            },
        ),
        migrations.CreateModel(
            name='FullLengthTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('listening', models.ManyToManyField(blank=True, limit_choices_to={'exam_type': 'Listening'}, null=True, related_name='listening', to='exam.exam')),
                ('reading', models.ManyToManyField(blank=True, limit_choices_to={'exam_type': 'Reading'}, null=True, related_name='reading', to='exam.exam')),
                ('speaking', models.ManyToManyField(blank=True, limit_choices_to={'exam_type': 'Speaking'}, null=True, to='exam.exam')),
            ],
        ),
    ]
