# Generated by Django 4.2 on 2023-12-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='block_threshold',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='block_type',
            field=models.CharField(choices=[('Practice', 'Practice'), ('Full Length', 'Full Length'), ('Both', 'Both')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20, null=True),
        ),
    ]
