# Generated by Django 4.2 on 2023-12-20 09:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_block_threshold_exam_block_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='passage',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
