# Generated by Django 4.2 on 2023-12-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_examtype_questiontype'),
        ('exam', '0004_rename_exam_name_exam_exam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='question_type',
        ),
        migrations.AddField(
            model_name='exam',
            name='question_type',
            field=models.ManyToManyField(null=True, to='master.questiontype'),
        ),
    ]
