# Generated by Django 4.2 on 2023-12-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_exam_question_type_exam_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='question_type',
        ),
    ]
