# Generated by Django 4.2 on 2023-12-22 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_moduletype'),
        ('exam', '0006_remove_exam_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='examblockaudio/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='type_of_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.moduletype'),
        ),
    ]
