# Generated by Django 4.2 on 2023-12-22 09:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_exam_audio_file_exam_type_of_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='passage',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
