# Generated by Django 4.2 on 2023-12-22 09:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_exam_passage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='passage',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contents'),
        ),
    ]
