# Generated by Django 4.2 on 2023-12-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_testtype'),
        ('exam', '0009_alter_exam_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='test_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.testtype'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Writing', 'Writing')], default='Reading', max_length=20),
        ),
        migrations.CreateModel(
            name='FullLengthTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('listening', models.ManyToManyField(limit_choices_to={'exam_type': 'Listening'}, related_name='listening', to='exam.exam')),
                ('reading', models.ManyToManyField(limit_choices_to={'exam_type': 'Reading'}, related_name='reading', to='exam.exam')),
                ('speaking', models.ManyToManyField(limit_choices_to={'exam_type': 'Speaking'}, to='exam.exam')),
                ('writing', models.ManyToManyField(limit_choices_to={'exam_type': 'Listening'}, related_name='writing', to='exam.exam')),
            ],
        ),
    ]
