# Generated by Django 4.2 on 2023-12-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_testtype'),
        ('exam', '0011_fulllengthtest_test_type_alter_exam_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulllengthtest',
            name='test_type',
            field=models.ForeignKey(help_text='IELTS/PTE etc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.testtype'),
        ),
    ]
