# Generated by Django 4.2 on 2023-12-22 14:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_alter_fulllengthtest_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='passage',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contents'),
        ),
    ]
