# Generated by Django 4.2 on 2024-01-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_alter_exam_passage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulllengthtest',
            name='listening',
            field=models.ManyToManyField(blank=True, limit_choices_to={'exam_type': 'Listening'}, null=True, related_name='listening', to='exam.exam'),
        ),
        migrations.AlterField(
            model_name='fulllengthtest',
            name='reading',
            field=models.ManyToManyField(blank=True, limit_choices_to={'exam_type': 'Reading'}, null=True, related_name='reading', to='exam.exam'),
        ),
        migrations.AlterField(
            model_name='fulllengthtest',
            name='speaking',
            field=models.ManyToManyField(blank=True, limit_choices_to={'exam_type': 'Speaking'}, null=True, to='exam.exam'),
        ),
        migrations.AlterField(
            model_name='fulllengthtest',
            name='writing',
            field=models.ManyToManyField(blank=True, limit_choices_to={'exam_type': 'Writing'}, null=True, related_name='writing', to='exam.exam'),
        ),
    ]
