# Generated by Django 4.2 on 2024-01-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_alter_fulllengthtest_listening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='test_type',
        ),
        migrations.AlterField(
            model_name='exam',
            name='block_type',
            field=models.CharField(choices=[('Practice', 'Practice'), ('Full Length', 'Full Length')], max_length=20, null=True),
        ),
    ]
