# Generated by Django 4.2 on 2024-01-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_remove_exam_test_type_alter_exam_block_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='block_type',
            field=models.CharField(choices=[('Practice', 'Practice'), ('Full Length', 'Full Length'), ('Assignments', 'Assignments')], max_length=20, null=True),
        ),
    ]
