# Generated by Django 4.2 on 2024-01-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0035_alter_batch_add_package'),
        ('exam', '0016_alter_exam_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.category'),
        ),
    ]
