# Generated by Django 4.2 on 2024-02-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_exam_exam_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='block_type',
            field=models.CharField(choices=[('Practice', 'Practice'), ('Full Length', 'Full Length'), ('Assignments', 'Assignments')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Writing', 'Writing')], default='Reading', help_text='(Reading, Listening, Speaking, Writing)', max_length=200),
        ),
    ]
