# Generated by Django 4.2 on 2024-02-05 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=255)),
                ('package_price', models.CharField(blank=True, max_length=100, null=True)),
                ('soft_copy', models.BooleanField(default=False)),
                ('hard_copy', models.BooleanField(default=False)),
                ('full_length_test', models.BooleanField(default=False)),
                ('full_length_test_count', models.PositiveIntegerField(default=0)),
                ('practice_test', models.BooleanField(default=False)),
                ('practice_test_count', models.PositiveIntegerField(default=0)),
                ('speaking_test', models.BooleanField(default=False)),
                ('speaking_test_count', models.PositiveIntegerField(default=0)),
                ('writing_evaluation', models.BooleanField(default=False)),
                ('live_classes_membership', models.BooleanField(default=False)),
                ('online_membership', models.BooleanField(default=False)),
                ('offline_membership', models.BooleanField(default=False)),
                ('group_doubt_solving', models.BooleanField(default=False)),
                ('group_doubt_solving_count', models.PositiveIntegerField(default=0)),
                ('one_to_one_doubt_solving', models.BooleanField(default=False)),
                ('one_to_one_doubt_solving_count', models.PositiveIntegerField(default=0)),
                ('validity', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='in_months', null=True)),
                ('PackageType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.packagetype')),
                ('coupon_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.cupon')),
                ('select_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
                ('user_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
