# Generated by Django 4.2 on 2023-12-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='in_months'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='validity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
