# Generated by Django 4.2 on 2023-12-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_duration_package_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Total_test',
        ),
        migrations.AddField(
            model_name='package',
            name='full_length_test_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='group_doubt_solving_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='one_to_one_doubt_solving_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='practice_test_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='speaking_test_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
