# Generated by Django 4.2 on 2023-12-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_remove_package_total_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='full_length_test_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='group_doubt_solving_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='one_to_one_doubt_solving_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='practice_test_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='speaking_test_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
