# Generated by Django 4.2 on 2023-12-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_package_coupen_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='coupen_code',
            new_name='coupon_code',
        ),
    ]
