# Generated by Django 4.2 on 2023-12-20 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_examtype_questiontype'),
        ('package', '0006_rename_coupen_code_package_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='coupon_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.cupon'),
        ),
    ]
