# Generated by Django 4.2 on 2024-01-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_package_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='user_profile',
        ),
    ]
