# Generated by Django 4.2 on 2024-01-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_package_package_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_user',
            new_name='user_package',
        ),
    ]
