# Generated by Django 4.2 on 2024-01-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_alter_package_user_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='user_package',
        ),
    ]
