# Generated by Django 4.2 on 2024-01-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0015_package_user_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='in_months', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
