# Generated by Django 4.2 on 2024-01-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0016_alter_package_duration_alter_package_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
