# Generated by Django 4.2 on 2024-02-05 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Create_Test', '0002_initial'),
        ('master', '0001_initial'),
        ('LiveClass', '0001_initial'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20)),
                ('phone_no', models.CharField(max_length=15, null=True)),
                ('whatsapp_no', models.CharField(max_length=15, null=True)),
                ('reference_by', models.TextField(null=True)),
                ('last_education', models.CharField(max_length=200, null=True)),
                ('ielts_taken_before', models.BooleanField(default=False)),
                ('duolingo_taken_before', models.BooleanField(default=False)),
                ('pte_taken_before', models.BooleanField(default=False)),
                ('toefl_taken_before', models.BooleanField(default=False)),
                ('gre_taken_before', models.BooleanField(default=False)),
                ('gmat_taken_before', models.BooleanField(default=False)),
                ('remark', models.TextField(null=True)),
                ('biography', models.TextField(null=True)),
                ('user_image', models.ImageField(null=True, upload_to='student_images/')),
                ('interested_in_visa_counselling', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50, null=True)),
                ('referal_code', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Live_class_enroll', models.ManyToManyField(blank=True, null=True, to='LiveClass.live_class')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_city', to='master.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_country', to='master.country')),
                ('country_interested_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_interest_country', to='master.country')),
                ('select_batch', models.ManyToManyField(blank=True, null=True, to='master.batch')),
                ('select_package', models.ManyToManyField(blank=True, null=True, to='package.package')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_state', to='master.state')),
                ('student_exam_block', models.ManyToManyField(blank=True, null=True, to='exam.exam')),
                ('student_module', models.ManyToManyField(blank=True, null=True, to='Create_Test.module')),
                ('user', models.OneToOneField(help_text='Create a student user first and then add the student details', on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
