# Generated by Django 5.0 on 2023-12-11 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20)),
                ('phone_no', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(max_length=15)),
                ('reference_by', models.TextField()),
                ('last_education', models.CharField(max_length=200)),
                ('ielts_taken_before', models.BooleanField(default=False)),
                ('duolingo_taken_before', models.BooleanField(default=False)),
                ('pte_taken_before', models.BooleanField(default=False)),
                ('toefl_taken_before', models.BooleanField(default=False)),
                ('gre_taken_before', models.BooleanField(default=False)),
                ('gmat_taken_before', models.BooleanField(default=False)),
                ('remark', models.TextField()),
                ('biography', models.TextField()),
                ('user_image', models.ImageField(upload_to='student_images/')),
                ('interested_in_visa_counselling', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_city', to='master.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_country', to='master.country')),
                ('country_interested_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_interest_country', to='master.country')),
                ('course_to_enroll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.course')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_state', to='master.state')),
            ],
        ),
    ]
