# Generated by Django 5.0 on 2023-12-11 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_to_enroll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.package'),
        ),
    ]
