# Generated by Django 5.0 on 2023-12-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_groups_student_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='amitv9433535', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
