# Generated by Django 5.0 on 2023-12-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name',
        ),
    ]
