# Generated by Django 4.2 on 2023-12-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_remove_batch_batch_timing'),
        ('package', '0002_package_duration_package_validity'),
        ('Courses', '0009_remove_course_course_price_and_more'),
        ('students', '0009_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='create_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='course_to_enroll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.package'),
        ),
    ]
