# Generated by Django 4.2 on 2023-12-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_date_created_student_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_updated',
            new_name='updated_at',
        ),
    ]
