# Generated by Django 4.2 on 2023-12-19 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_remove_section_course'),
        ('Courses', '0014_course_course_identifier'),
        ('students', '0012_rename_date_created_student_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='create_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='create_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interested_in_visa_counselling',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_education',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_by',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_image',
            field=models.ImageField(null=True, upload_to='student_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='whatsapp_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
