# Generated by Django 4.2 on 2023-12-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_student_referal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='referal_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
