# Generated by Django 4.2 on 2024-01-10 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_alter_package_user_package'),
        ('students', '0018_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_to_enroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package.package'),
        ),
    ]
