# Generated by Django 4.2 on 2024-01-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0015_course_tutor'),
        ('master', '0024_batch_batchuser'),
        ('students', '0019_alter_student_course_to_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='create_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='create_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.course'),
        ),
    ]
