# Generated by Django 4.2 on 2024-01-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0025_alter_batch_batch_name'),
        ('students', '0020_alter_student_create_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_to_enroll',
        ),
        migrations.RemoveField(
            model_name='student',
            name='create_course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='create_batch',
        ),
        migrations.AddField(
            model_name='student',
            name='create_batch',
            field=models.ManyToManyField(to='master.batch'),
        ),
    ]
