# Generated by Django 4.2 on 2024-01-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0027_remove_batch_create_course'),
        ('students', '0021_remove_student_course_to_enroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='create_batch',
            field=models.ManyToManyField(blank=True, null=True, to='master.batch'),
        ),
    ]
