# Generated by Django 4.2 on 2024-01-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_student_create_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='create_batch',
            new_name='select_batch',
        ),
    ]
