# Generated by Django 4.2 on 2024-01-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_rename_create_batch_student_select_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='create_package',
            new_name='select_package',
        ),
    ]
