# Generated by Django 4.2 on 2024-01-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveClass', '0005_remove_live_class_live_class_user'),
        ('students', '0025_rename_create_package_student_select_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Live_class_enroll',
            field=models.ManyToManyField(blank=True, null=True, to='LiveClass.live_class'),
        ),
    ]
