# Generated by Django 4.2 on 2024-02-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_exam_exam_category'),
        ('Create_Test', '0005_alter_responses_responses_listening_and_more'),
        ('students', '0026_student_live_class_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_exam_block',
            field=models.ManyToManyField(blank=True, null=True, to='exam.exam'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_module',
            field=models.ManyToManyField(blank=True, null=True, to='Create_Test.module'),
        ),
    ]
