version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    restart: on-failure
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    ports:
      - '5432:5432'
    volumes: 
      - pgdb:/var/lib/postgresql/data
  backend:
    build: .
    restart: on-failure
    container_name: lms
    # command: sh -c "gunicorn --config gunicorn_config.py /app/powercrm.wsgi:application"
    expose:
      - "8000"
    volumes:
      - ./:/app
      - staticfiles:/var/www/static/
      - /var/certbot/conf:/etc/letsencrypt/:ro
    env_file:
      - ./.env
    environment:
      - STATIC_ROOT=/var/www/static/

    depends_on:
      - postgres_db
    command: ["./wait-for-it.sh", "postgres_db:5432", "--", "./entrypoint.sh"]

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staticfiles:/home/app/staticfiles/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./front/:/usr/share/nginx/html/
    depends_on:
      - backend
volumes:
  pgdb:
  staticfiles: