# Generated by Django 4.2 on 2024-02-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=100)),
                ('zoom_meeting_password', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
