# Generated by Django 4.2 on 2024-01-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveClass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='live_class',
            old_name='batch',
            new_name='select_batch',
        ),
    ]
