# Generated by Django 4.2 on 2024-01-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0034_live_class_type'),
        ('LiveClass', '0002_rename_batch_live_class_select_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_class',
            name='liveclasstype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.live_class_type'),
            preserve_default=False,
        ),
    ]
