# Generated by Django 4.2 on 2024-01-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveClass', '0004_live_class_live_class_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live_class',
            name='live_class_user',
        ),
    ]
