# Generated by Django 4.2 on 2024-01-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveClass', '0005_remove_live_class_live_class_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_class',
            name='zoom_meeting_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
