# Generated by Django 4.2 on 2024-01-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveClass', '0006_alter_live_class_zoom_meeting_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_class',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='live_class',
            name='zoom_meeting_password',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
