# Generated by Django 4.2 on 2024-01-31 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0035_alter_batch_add_package'),
        ('LiveClass', '0007_alter_live_class_zoom_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_class',
            name='liveclasstype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.live_class_type'),
        ),
    ]
