# Generated by Django 4.2 on 2024-01-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveClass', '0008_alter_live_class_liveclasstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_class',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='live_class',
            name='meeting_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='live_class',
            name='meeting_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='live_class',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
