# Generated by Django 4.2 on 2024-01-30 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0016_alter_course_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursedetail', '0010_quizoption_correct_answer'),
        ('Activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoursesActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('Courses', models.ManyToManyField(blank=True, to='Courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonsActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('lessons', models.ManyToManyField(blank=True, to='coursedetail.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='course',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
