# Generated by Django 4.2 on 2024-01-31 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0016_alter_course_description_and_more'),
        ('Activities', '0003_userquizactivity_userassessmentactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFullLengthTestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('Courses', models.ManyToManyField(blank=True, to='Courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
