# Generated by Django 5.0 on 2023-12-13 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0001_initial'),
        ('master', '0009_alter_batch_batch_name'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.batch'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package.package'),
        ),
    ]
