# Generated by Django 5.0 on 2023-12-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0002_liveclass_batch_liveclass_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveclass',
            options={'verbose_name_plural': 'LiveClasses'},
        ),
    ]
