# Generated by Django 4.2 on 2024-01-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0003_alter_liveclass_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='zoom_meeting_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
