# Generated by Django 4.2 on 2024-01-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0030_liveclasstype'),
        ('live_classes', '0003_alter_liveclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='live_class_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='live_class_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.liveclasstype'),
            preserve_default=False,
        ),
    ]
