# Generated by Django 4.2 on 2024-01-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0003_alter_liveclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveclass',
            options={'verbose_name_plural': 'Live Classes'},
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='course',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='package',
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='zoom_meeting_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
