# Generated by Django 4.2 on 2024-01-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0004_alter_liveclass_options_remove_liveclass_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveclass',
            options={'verbose_name_plural': 'LiveClasses'},
        ),
    ]
