# Generated by Django 4.2 on 2024-01-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0004_alter_liveclass_zoom_meeting_id'),
        ('live_classes', '0005_alter_liveclass_options'),
    ]

    operations = [
    ]
