# Generated by Django 4.2 on 2024-01-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0006_merge_20240118_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
