# Generated by Django 5.0 on 2023-12-11 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuestionBank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listening', models.ManyToManyField(to='QuestionBank.listening_question')),
                ('Reading', models.ManyToManyField(to='QuestionBank.readingquestion')),
                ('Speaking', models.ManyToManyField(to='QuestionBank.speakingquestion')),
                ('Writing', models.ManyToManyField(to='QuestionBank.writingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='createexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IELTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTest.module')),
            ],
        ),
    ]
