# Generated by Django 4.2 on 2024-01-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_exam_exam_category'),
        ('CreateTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='Reading',
            field=models.ManyToManyField(blank=True, null=True, to='exam.exam'),
        ),
    ]
