# Generated by Django 4.2 on 2024-01-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTest', '0002_alter_module_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='Listening',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Speaking',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Writing',
        ),
    ]
