# Generated by Django 4.2 on 2024-01-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0001_initial'),
        ('CreateTest', '0003_remove_module_listening_remove_module_speaking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='Listening',
            field=models.ManyToManyField(to='QuestionBank.listening_question'),
        ),
        migrations.AddField(
            model_name='module',
            name='Speaking',
            field=models.ManyToManyField(to='QuestionBank.speakingquestion'),
        ),
        migrations.AddField(
            model_name='module',
            name='Writing',
            field=models.ManyToManyField(to='QuestionBank.writingquestion'),
        ),
    ]
