# Generated by Django 4.2 on 2024-01-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_exam_exam_category'),
        ('CreateTest', '0004_module_listening_module_speaking_module_writing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='Speaking',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Writing',
        ),
        migrations.AlterField(
            model_name='module',
            name='Listening',
            field=models.ManyToManyField(related_name='Listening', to='exam.exam'),
        ),
    ]
