# Generated by Django 4.2 on 2024-01-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_exam_exam_category'),
        ('CreateTest', '0005_remove_module_speaking_remove_module_writing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='Speaking',
            field=models.ManyToManyField(blank=True, null=True, related_name='Speaking+', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='module',
            name='Writing',
            field=models.ManyToManyField(blank=True, null=True, related_name='writing+', to='exam.exam'),
        ),
        migrations.AlterField(
            model_name='module',
            name='Listening',
            field=models.ManyToManyField(blank=True, null=True, related_name='listening+', to='exam.exam'),
        ),
    ]
