# Generated by Django 4.2 on 2024-01-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTest', '0006_module_speaking_module_writing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
