# Generated by Django 5.0 on 2023-12-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_batch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='name',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_name',
            field=models.TimeField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_timing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
