# Generated by Django 5.0 on 2023-12-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_course_course_material'),
        ('master', '0003_remove_batch_name_batch_batch_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.course'),
        ),
    ]
