# Generated by Django 5.0 on 2023-12-13 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0009_remove_lesson_lesson_attachment'),
        ('master', '0004_section_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lesson_attachment', models.FileField(blank=True, default=None, null=True, upload_to='documents/')),
                ('Lesson_attachment_description', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedetail.lesson')),
            ],
        ),
    ]
