# Generated by Django 5.0 on 2023-12-13 09:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_rename_lesson_attachment_lessonattachment_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometakeywords',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
