# Generated by Django 5.0 on 2023-12-13 09:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_seometakeywords_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometakeywords',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=200), blank=True, size=None),
        ),
    ]
