# Generated by Django 4.2 on 2023-12-14 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_batch_batch_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seometakeywords',
            options={'verbose_name_plural': 'SEOMetakeywords'},
        ),
    ]
