# Generated by Django 4.2 on 2023-12-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_seometakeywords_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcomes',
            options={'verbose_name_plural': 'Outcomes'},
        ),
        migrations.AlterModelOptions(
            name='requirements',
            options={'verbose_name_plural': 'Requirements'},
        ),
    ]
