# Generated by Django 5.0 on 2023-12-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_alter_outcomes_options_alter_requirements_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Catergories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
