# Generated by Django 4.2 on 2023-12-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
        ('Courses', '0008_course_course_delivery_course_course_type'),
        ('master', '0012_alter_batch_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='add_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='add_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='package.package'),
            preserve_default=False,
        ),
    ]
