# Generated by Django 4.2 on 2023-12-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_batch_add_course_batch_add_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='add_course',
            new_name='create_course',
        ),
    ]
