# Generated by Django 4.2 on 2023-12-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_remove_section_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon_name', models.CharField(max_length=200, null=True)),
                ('campaign_name', models.CharField(max_length=50)),
                ('cupon_code', models.CharField(max_length=50)),
                ('discount', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
