# Generated by Django 4.2 on 2023-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_examtype_questiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(max_length=100)),
            ],
        ),
    ]
