# Generated by Django 4.2 on 2024-01-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0024_batch_batchuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
