# Generated by Django 4.2 on 2024-01-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0025_alter_batch_batch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batchuser',
        ),
    ]
