# Generated by Django 4.2 on 2024-01-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_remove_batch_batchuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='create_course',
        ),
    ]
