# Generated by Django 4.2 on 2024-01-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0014_remove_package_user_package'),
        ('master', '0027_remove_batch_create_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='add_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='package.package'),
        ),
    ]
