# Generated by Django 4.2 on 2024-01-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0028_alter_batch_add_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='material_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
