# Generated by Django 4.2 on 2024-01-25 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0017_alter_package_package_name'),
        ('master', '0034_live_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='add_package',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='package.package'),
            preserve_default=False,
        ),
    ]
