# Generated by Django 5.0 on 2023-12-11 07:50

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listening_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Audio', models.FileField(upload_to='audio/')),
                ('Instructions', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestionTypeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPassageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingQuestionTypeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingQuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WritingQuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listening_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(blank=True, max_length=200, null=True)),
                ('Correct_Answer', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.listening_question')),
            ],
        ),
        migrations.AddField(
            model_name='listening_question',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.listeningquestion'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.listeningquestiontypename'),
        ),
        migrations.CreateModel(
            name='ReadingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answers', models.CharField(blank=True, max_length=200, null=True)),
                ('Corect_Answer', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.reading_question')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instructions', ckeditor.fields.RichTextField()),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.readingpassagename')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.readingquestiontypename')),
            ],
        ),
        migrations.AddField(
            model_name='reading_question',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.readingquestion'),
        ),
        migrations.CreateModel(
            name='SpeakingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Audio', models.FileField(upload_to='audio/')),
                ('Instructions', ckeditor.fields.RichTextField()),
                ('Ans', ckeditor.fields.RichTextField()),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.speakingquestiontype')),
            ],
        ),
        migrations.CreateModel(
            name='WritingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instructions', ckeditor.fields.RichTextField()),
                ('Ans', ckeditor.fields.RichTextField()),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.writingquestiontype')),
            ],
        ),
    ]
