# Generated by Django 4.2 on 2024-02-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_alter_exam_passage'),
        ('Studentanswer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exam.exam'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question_number',
            field=models.IntegerField(),
        ),
    ]
