# Generated by Django 4.2 on 2024-02-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Studentanswer', '0002_alter_studentanswer_exam_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
