# Generated by Django 4.0.3 on 2023-11-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursedetail', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Title', models.CharField(max_length=200)),
                ('Short_Description', models.TextField()),
                ('Description', models.TextField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Featured', models.BooleanField(default=False)),
                ('Support_Available', models.BooleanField(default=False)),
                ('Course_Price', models.PositiveIntegerField()),
                ('Discount_in_percent', models.PositiveIntegerField()),
                ('Course_Overview_Provider', models.CharField(max_length=200)),
                ('Course_Overview_URL', models.URLField()),
                ('Course_Thumbnail', models.ImageField(upload_to='course_thumbnails/')),
                ('SEO_Meta_Keywords', models.TextField()),
                ('Meta_Description', models.TextField()),
                ('Batch_Timing', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='master.batch')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.category')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.language')),
                ('Lessons', models.ManyToManyField(blank=True, to='coursedetail.lesson')),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.level')),
                ('Outcome', models.ManyToManyField(to='master.outcomes')),
                ('Requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.requirements')),
            ],
        ),
    ]
