# Generated by Django 5.0 on 2023-12-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='EndDate',
            new_name='EnrollmentEndDate',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='StartDate',
            new_name='EnrollmentStartDate',
        ),
    ]
