# Generated by Django 5.0 on 2023-12-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_rename_enddate_course_enrollmentenddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_count',
            field=models.IntegerField(default=0),
        ),
    ]
