# Generated by Django 5.0 on 2023-12-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_enrollment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faqs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='max_enrollments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
