# Generated by Django 5.0 on 2023-12-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_course_faqs_course_is_active_course_max_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
