# Generated by Django 5.0 on 2023-12-13 09:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_course_course_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Meta_Description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=200), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='SEO_Meta_Keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=200), blank=True, size=None),
        ),
    ]
