# Generated by Django 5.0 on 2023-12-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_alter_course_meta_description_and_more'),
        ('master', '0009_alter_batch_batch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Requirements',
        ),
        migrations.AddField(
            model_name='course',
            name='Requirements',
            field=models.ManyToManyField(to='master.requirements'),
        ),
    ]
