# Generated by Django 4.2 on 2023-12-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_remove_batch_batch_timing'),
        ('package', '0002_package_duration_package_validity'),
        ('Courses', '0008_course_course_delivery_course_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Course_Price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Discount_in_percent',
        ),
        migrations.AddField(
            model_name='course',
            name='add_batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='master.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='add_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='package.package'),
            preserve_default=False,
        ),
    ]
