# Generated by Django 4.2 on 2023-12-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0011_remove_course_batch_timing_remove_course_add_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_material',
        ),
    ]
