# Generated by Django 4.2 on 2023-12-18 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0012_remove_course_course_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_count',
        ),
        migrations.AddField(
            model_name='course',
            name='primary_instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
