# Generated by Django 4.2 on 2023-12-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0013_remove_course_enrollment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_identifier',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
