# Generated by Django 4.2 on 2024-01-17 06:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0015_course_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='Short_Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='faqs',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
