# Generated by Django 4.2 on 2024-01-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0017_alter_course_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tutor',
        ),
    ]
