# Generated by Django 4.2 on 2024-01-31 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Courses', '0019_course_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='primary_instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ManyToManyField(related_name='tutor', to='auth.group'),
        ),
    ]
