# Generated by Django 4.2 on 2024-01-31 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0020_alter_course_primary_instructor_alter_course_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='primary_instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ManyToManyField(related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
