# Generated by Django 4.2 on 2024-01-31 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0022_alter_course_primary_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Tutor'}, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
