# Generated by Django 5.0 on 2023-12-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuestionBank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Writing_Exam', models.ManyToManyField(to='QuestionBank.readingquestion')),
            ],
        ),
    ]
