# Generated by Django 4.2 on 2024-02-08 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0002_initial'),
        ('ExamResponses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_answer',
            name='student_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamResponses.studentanswer'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
