# Generated by Django 4.2 on 2024-02-05 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0002_initial'),
        ('ExamResponses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.exam'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
