# Generated by Django 4.2 on 2024-02-05 12:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('module_category', models.CharField(blank=True, max_length=220, null=True)),
                ('exam_test', models.CharField(blank=True, choices=[('Practice', 'Practice'), ('Full Length', 'Full Length')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses_reading', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=500), blank=True, null=True, size=None)),
                ('responses_listening', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=500), blank=True, null=True, size=None)),
                ('responses_writing', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=500), blank=True, null=True, size=None)),
                ('responses_speaking', models.FileField(blank=True, null=True, upload_to='responses_audio/')),
            ],
        ),
    ]
