# Generated by Django 4.2 on 2024-01-31 13:43

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0017_exam_exam_category'),
        ('Create_Test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses_reading', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=200), blank=True, size=None)),
                ('responses_listening', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=200), blank=True, size=None)),
                ('responses_writing', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=200), blank=True, size=None)),
                ('responses_speaking', models.FileField(upload_to='responses_audio/')),
                ('exam', models.ManyToManyField(blank=True, null=True, to='exam.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
