# Generated by Django 4.2 on 2024-01-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_exam_exam_category'),
        ('Create_Test', '0003_alter_responses_responses_listening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='exam',
        ),
        migrations.AddField(
            model_name='responses',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
