# Generated by Django 4.2 on 2024-02-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together=set(),
        ),
    ]
