# Generated by Django 4.2 on 2024-02-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Responses', '0002_alter_studentanswer_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='question_number',
        ),
        migrations.CreateModel(
            name='Student_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('answer_text', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='Exam_Responses.studentanswer')),
            ],
        ),
    ]
