# Generated by Django 4.2 on 2024-02-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_alter_exam_block_type_alter_exam_difficulty_level_and_more'),
        ('Exam_Responses', '0003_remove_studentanswer_answer_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_answer',
            name='exam',
        ),
        migrations.AddField(
            model_name='student_answer',
            name='student_exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_exam', to='Exam_Responses.studentanswer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.exam'),
            preserve_default=False,
        ),
    ]
