# Generated by Django 4.2 on 2024-02-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_alter_exam_block_type_alter_exam_difficulty_level_and_more'),
        ('Exam_Responses', '0004_remove_student_answer_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.exam'),
        ),
    ]
