# Generated by Django 4.2 on 2024-02-05 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lesson_Title', models.CharField(default=None, max_length=200)),
                ('Lesson_Description', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Lesson_Video', models.URLField(blank=True, default=None, null=True)),
                ('Lesson_Duration', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(blank=True, max_length=200, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedetail.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answers', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_answer', models.BooleanField(default=False, verbose_name='Is this correct?')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedetail.quiz_question')),
            ],
        ),
    ]
