# Generated by Django 5.0 on 2023-12-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Lesson_Video',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
