# Generated by Django 5.0 on 2023-12-12 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0002_alter_lesson_lesson_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lession_Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coursedetail.lession_quiz'),
            preserve_default=False,
        ),
    ]
