# Generated by Django 5.0 on 2023-12-12 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0003_lession_quiz_lesson_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='quiz',
        ),
        migrations.AddField(
            model_name='lession_quiz',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='coursedetail.lesson'),
            preserve_default=False,
        ),
    ]
