# Generated by Django 5.0 on 2023-12-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0006_remove_question_quiz_reading_question_readingoption_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reading_Question',
            new_name='Quiz_Question',
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answers', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedetail.quiz_question')),
            ],
        ),
        migrations.DeleteModel(
            name='ReadingOption',
        ),
    ]
