# Generated by Django 5.0 on 2023-12-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0007_rename_reading_question_quiz_question_quizoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Lesson_Title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
