# Generated by Django 5.0 on 2023-12-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0008_alter_lesson_lesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='Lesson_attachment',
        ),
    ]
