# Generated by Django 5.0 on 2023-12-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0009_remove_lesson_lesson_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizoption',
            name='correct_answer',
            field=models.BooleanField(default=False, verbose_name='Is this correct?'),
        ),
    ]
