# Generated by Django 4.2 on 2024-01-23 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_alter_exam_passage'),
        ('coursedetail', '0010_quizoption_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
