# Generated by Django 4.2 on 2024-01-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0011_alter_quiz_question_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizoption',
            name='name',
        ),
        migrations.DeleteModel(
            name='Quiz_Question',
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
    ]
