# Generated by Django 4.2 on 2024-01-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_alter_fulllengthtest_listening_and_more'),
        ('coursedetail', '0012_remove_quizoption_name_delete_quiz_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_assignment',
            field=models.ManyToManyField(related_name='lesson_assignment', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_quiz',
            field=models.ManyToManyField(to='exam.exam'),
        ),
    ]
