# Generated by Django 4.2 on 2024-01-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0014_remove_lesson_lesson_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(blank=True, max_length=200, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedetail.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answers', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_answer', models.BooleanField(default=False, verbose_name='Is this correct?')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedetail.quiz_question')),
            ],
        ),
    ]
