# Generated by Django 4.2 on 2024-01-29 09:01

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0015_quiz_question_quizoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contents')),
                ('no_of_questions', models.IntegerField(default=4)),
                ('question', ckeditor.fields.RichTextField()),
                ('exam_type', models.CharField(choices=[('Reading', 'Reading'), ('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Writing', 'Writing')], default='Reading', help_text='(Reading, Listening, Speaking, Writing)', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('answer_text', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='coursedetail.assignment_question')),
            ],
        ),
    ]
