# Generated by Django 4.2 on 2024-01-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0016_assignment_question_assignment_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment_Answer',
        ),
        migrations.DeleteModel(
            name='Assignment_Question',
        ),
    ]
