# Generated by Django 4.2 on 2024-01-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_alter_exam_block_type'),
        ('coursedetail', '0018_lesson_lesson_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_assignment',
            field=models.ManyToManyField(blank=True, null=True, related_name='lesson_assignment', to='exam.exam'),
        ),
    ]
